FROM python:3.12-slim

# создаем воркдир
WORKDIR /app

# копируем содержимое текущей папки в контейнер
COPY . .

# подтягиваем зависимости из requirements
RUN pip install --no-cache-dir -r requirements.txt

# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]

